name: Ubuntu Desktop (Tailscale Access)

on:
  workflow_dispatch:

jobs:
  setup-ubuntu-desktop:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Update System & Install Desktop Environment
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          
          # Install lightweight desktop and VNC server
          sudo apt install -y xfce4 xfce4-goodies xrdp dbus-x11 x11-xserver-utils
          
          # Enable and start XRDP service
          sudo systemctl enable xrdp
          sudo systemctl start xrdp
          
          # Create RDP user
          USERNAME=rdpuser
          PASSWORD=$(openssl rand -base64 12)
          sudo useradd -m -s /bin/bash $USERNAME
          echo "$USERNAME:$PASSWORD" | sudo chpasswd
          sudo usermod -aG sudo $USERNAME
          
          echo "RDP_CREDS=User: $USERNAME | Password: $PASSWORD" >> $GITHUB_ENV

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-$GITHUB_RUN_ID --accept-routes --ssh

          # Wait for Tailscale IP
          TS_IP=$(tailscale ip -4 | head -n 1)
          echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV
          echo "Tailscale IP: $TS_IP"

      - name: Verify XRDP service
        run: |
          sudo systemctl status xrdp --no-pager
          sudo ss -tuln | grep 3389 || echo "RDP port not listening"

      - name: Display Connection Info
        run: |
          echo ""
          echo "==============================="
          echo "✅ Ubuntu Desktop Access Ready!"
          echo "==============================="
          echo "Tailscale IP: $TAILSCALE_IP"
          echo "Username: $(echo $RDP_CREDS | cut -d' ' -f2)"
          echo "Password: $(echo $RDP_CREDS | cut -d' ' -f4)"
          echo "==============================="
          echo "🔗 Connect using any RDP client (Windows, Mac, or Remmina on Linux)"
          echo "Example: mstsc /v:$TAILSCALE_IP"
          echo ""
          echo "Session will remain active for up to 1 hour unless stopped."

      - name: Keep Session Active
        run: |
          while true; do
            echo "[$(date)] Ubuntu Desktop Active - Connected via Tailscale ($TAILSCALE_IP)"
            sleep 300
          done
